### ISSUE TITLE
expectDeprecation*(): Document custom extension + events approach for PHPUnit 10

### ISSUE THREAD

**Issue by hellofromtonya** [Yoast/PHPUnit-Polyfills#185]
[PHPUnit 10 removed](https://github.com/sebastianbergmann/phpunit/issues/5062) the `expect*()` methods, including `expectDeprecation()`, `expectDeprecationMessage()`, and `expectDeprecationMessageMatches()`.

As PHPUnit Polyfills is forward compatible, these removed expectations will not be polyfilled in 2.x. 

As it is possible to polyfill these removed expectations, @jrfnl and I discussed documenting a custom approach in the 2.x README's FAQ.

The custom approach:
- takes inspiration from PHPUnit 11: refer to [the Error Handling > Expecting Deprecations docs](https://docs.phpunit.de/en/11.3/error-handling.html#expecting-deprecations-e-user-deprecated) and [the PR that implemented it](https://github.com/sebastianbergmann/phpunit/pull/5605).
- adds [an extension](https://docs.phpunit.de/en/10.5/extending-phpunit.html#implementing-an-extension).
- uses [the `PHPUnit\Event\Test\` events](https://docs.phpunit.de/en/10.5/events.html#test).

**Comment by jrfnl** [comment]
Closing as duplicate (or close ) of #186.
