### ISSUE TITLE
[FR] Handle removed assertAttribute*() assertions

### ISSUE THREAD

**Issue by jrfnl** [Yoast/PHPUnit-Polyfills#2]
A whole slew of `assertAttribute*() assertions were deprecated in PHPUnit 8.0.0 and removed in PHPUnit 9.0.0 without replacement.

The reasoning behind the removal was that it was too easy to test private/protected properties which should be considered implementation details and that those should not be tested directly.

Polyfilling this would require copying most of the removed code from PHPUnit, which I'm hesistant to do.

Refs:
* https://github.com/sebastianbergmann/phpunit/issues/3338
* https://github.com/sebastianbergmann/phpunit/issues/3339

**Comment by erickskrauch** [comment]
Hello. I'm interested in this feature. I would be happy to provide a pull request, but I don't quite understand the part of your "which I'm hesistant to do" message. Why don't you want to copy the code of PHPUnit?

**Comment by jrfnl** [comment]
@erickskrauch Thanks for asking.

> I don't quite understand the part of your "which I'm hesistant to do" message. Why don't you want to copy the code of PHPUnit?

There are two reasons why I'm not keen on this:
1. I tend to agree with @sebastianbergmann's reasoning for removing the functionality.
2. I don't think ripping off other people's code is the polite thing to do. Open source does not mean copyright doesn't apply.

Generally speaking, you'll find that the polyfills in this package use the underlying functionality in PHPUnit as-is without copying over large chunks of new/removed code.

All the same, I do recognize that refactoring the code or the tests of a package to work around the removal of the `assertAttribute*()` methods may take some time and that people, in the mean time, do want to use this library to allow for testing their code on PHP 8.0.

With this in mind, I've implemented some helper functions which will allow for testing private and protected attributes without duplicating the original functionality from PHPUnit. You can find the new functionality here: https://github.com/Yoast/PHPUnit-Polyfills/commit/45c6489f7ad3381ec43279543eaf3a38f478388c

I'd be interested to hear if you think this is a workable enough compromise.

**Comment by jrfnl** [comment]
@erickskrauch Just checking in to see whether you've had a chance to look at the alternative implementation.

**Comment by erickskrauch** [comment]
@jrfnl, hello. I'm sorry for the delay, right now have no possibility to work on a project, where I need this functionality. I hope I'll be able to return to it within a week.

**Comment by jrfnl** [comment]
@erickskrauch Thanks for getting back to me. Let me know how you get on.

**Comment by jrfnl** [comment]
Closing as fixed via the `Helpers\AssertAttributeHelper` as added in https://github.com/Yoast/PHPUnit-Polyfills/commit/45c6489f7ad3381ec43279543eaf3a38f478388c
