### ISSUE TITLE
[FR] Handle removed assertEqualXMLStructure() assertion

### ISSUE THREAD

**Issue by jrfnl** [Yoast/PHPUnit-Polyfills#3]
The `Assert::assertEqualXMLStructure()` assertion was deprecated in PHPUnit 9.1.0 and will be removed in PHPUnit 10.0.0 without replacement.

Polyfilling this would require copying most of the code which will be removed from PHPUnit, which I'm hesistant to do.

Refs:
* https://github.com/sebastianbergmann/phpunit/issues/4091
* https://github.com/sebastianbergmann/phpunit/issues/4092

**Comment by stof** [comment]
As this library is described as a forward-compatibility polyfill, I would say that adding back support for removed assertions is out of scope.
The forward-compatibility polyfill would be to remove these assertions on older versions too, which would be weird.

**Comment by jrfnl** [comment]
@stof Exactly why it hasn't been done yet. I've opened issues for several of these removals to see how much need/interest there is to polyfill them anyway and we'll take it from there based on :+1: / :-1: 's.

**Comment by jrfnl** [comment]
Update: the removal has been executed in PHPUnit upstream: https://github.com/sebastianbergmann/phpunit/commit/47a2d9218f294ef5b096016a5d26f3bf55ad025e

**Comment by jrfnl** [comment]
Update: there is discussion about replacing the functionality with different, improved implementations in: https://github.com/sebastianbergmann/phpunit/issues/4091
Also see: https://github.com/sebastianbergmann/phpunit/pull/4507

**Comment by jrfnl** [comment]
Not seeing any movement on this upstream, nor significant interest here, so I'm closing this issue. If upstream decides to add a replacement, we'll deal with it, but there nothing to do until that time.
