### ISSUE TITLE
Running the Tests in CI

### ISSUE THREAD

**Issue by nadar** [Yoast/PHPUnit-Polyfills#7]
> First of all, this package is what i was looking for since months. I don't understand why the defacto standard testing library phpunit does not support a wide range of php versions, this just makes no sense to me. (The composer packages and libraries itself should make the php version restriction, not the test system). Anyhow!

When running `vendor/bin/phpunit --verbose --configuration actions.phpunit.xml` in "not supported" php versions the output is `This version of PHPUnit is supported on PHP 7.3 and PHP 7.4.` (see https://github.com/luyadev/luya-testsuite/pull/39/checks?check_run_id=1485397698) 

Do we have to change anything regarding how to run the test suite?

Thanks for your work!

**Comment by jrfnl** [comment]
@nadar Glad to hear you like what I've done here.

I've left a few comments on the PR you refer to above to help you solve this issue.

The short version: don't use `--ignore-platform-reqs` unless you really need to.

**Comment by jrfnl** [comment]
@nadar Based on the build for PR https://github.com/luyadev/luya-testsuite/pull/39 now passing I presume we can close this issue ?

**Comment by nadar** [comment]
@jrfnl Yes, indeed. Thanks for the help and for the perfect package!

**Comment by jrfnl** [comment]
You're welcome, may it serve you well.
