### ISSUE TITLE
PHPUnit 10 support?

### ISSUE THREAD

**Issue by dingo-d** [Yoast/PHPUnit-Polyfills#82]
Will this package have PHPUnit 10 support? 

Seeing how PHPUnit 10 will only work with PHP 8.1 and above, not sure if that would clash with this package. And v10 is a pretty big rewrite from what I gathered.

I tried to test one lib that I'm contributing to on PHP 8.2 and got into dependency issues, where some packages required certain versions of PHPUnit, and I noticed that polyfills support PHPUnit up to v9.

**Comment by jrfnl** [comment]
@dingo-d 100% the intention. Prelim work for this has already been done and I have a local branch with some additional changes, which is waiting for a PHPUnit 10-RC before I pull it.

The only big challenge I currently see is the changes in/removal of the test listeners and I still need figure out if the Polyfills can continue to provide a cross-version compatible test listener implementation.

The tests for this package are also already being run against PHPUnit 10 and aside from the testlisteners, there are [no incompatibilities at this time](https://github.com/Yoast/PHPUnit-Polyfills/runs/7645821795?check_suite_focus=true).

Note: the above statements are based on the premise of the Polyfills remaining unchanged, i.e. providing a _forward-compatible_ layer. So functionality which is removed from PHPUnit without replacement will not be handled by the PHPUnit Polyfills.

**Comment by jrfnl** [comment]
I'm closing this issue as until there is a PHPUnit 10-RC release, there is nothing to be done here. All the same, I will pin this issue for visibility as I can imagine other people may have the same question in the near future.

**Comment by stof** [comment]
@jrfnl as PHPUnit 10 is now stable, should this be re-opened ?

**Comment by jrfnl** [comment]
@stof Good point. I'll be working on this once I'm back from my break. Also see: https://phpc.social/@jrf_nl/109800368057494777

**Comment by Stevemoretz** [comment]
Any news on this?

**Comment by jrfnl** [comment]
@Stevemoretz I've just come back from my break. Working through my email backlog now. Working on this is my next priority after that.

**Comment by Stevemoretz** [comment]
> @Stevemoretz I've just come back from my break. Working through my email backlog now. Working on this is my next priority after that.

Thanks for the update and the great work!

**Comment by jrfnl** [comment]
Everyone: I've opened [an issue with the roadmap for the PHPUnit Polyfills version to support PHPUnit 10.0](https://github.com/Yoast/PHPUnit-Polyfills/issues/95).

I'd appreciate it if you could have a read-through and would leave comments if there if there is anything in the roadmap which concerns you.

**Comment by jrfnl** [comment]
Closing as [version 2.0.0](https://github.com/Yoast/PHPUnit-Polyfills/releases/tag/2.0.0) has been released.
